/*******************************************************************************
 * Copyright  
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package net.mjrz.fm.ui.panels.prefs;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class DisplayPrefsPanel extends javax.swing.JPanel implements
		PreferencesPanel {

	private static final long serialVersionUID = 1L;
	private static final String[] formats = { "EEE, MMM d, ''yy", "yyyy/MM/dd",
			"MM/dd/yyyy", "dd/MM/yyyy" };

	/** Creates new form DisplayPrefsDialog */
	public DisplayPrefsPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		Date now = new Date();
		String dateFormats[] = new String[formats.length];
		for (int i = 0; i < formats.length; i++) {
			SimpleDateFormat sdf = new SimpleDateFormat(formats[i]);
			dateFormats[i] = sdf.format(now);
		}
		dateFormatCb = new javax.swing.JComboBox();

		jLabel1.setText("Date format");

		dateFormatCb
				.setModel(new javax.swing.DefaultComboBoxModel(dateFormats));
		dateFormatCb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dateFormatCbActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 105,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(dateFormatCb, 0, 140, Short.MAX_VALUE)
						.addGap(127, 127, 127)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(40, 40, 40)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														dateFormatCb,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(240, Short.MAX_VALUE)));
	}// </editor-fold>

	private void dateFormatCbActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JComboBox dateFormatCb;
	private javax.swing.JLabel jLabel1;

	// End of variables declaration

	@Override
	public Map<String, Object> getPreferences() {
		HashMap<String, Object> ret = new HashMap<String, Object>();
		int sel = dateFormatCb.getSelectedIndex();
		if (sel < 0) {
			sel = 0;
		}
		ret.put("UIPrefs.DateFormat", formats[sel]);
		return ret;
	}
}
