/*******************************************************************************
 * Copyright  
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package net.mjrz.fm.ui.dialogs.filter;

import javax.swing.JDialog;

public class DateSelectorPanel extends javax.swing.JPanel implements
		FilterValueSelector {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Object selectedObject;
	private JDialog parent;

	/** Creates new form DateSelectorPanel */
	public DateSelectorPanel(JDialog parent) {
		this.parent = parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		dateSelectorCb = new javax.swing.JComboBox();

		jLabel1.setText("Select:");

		dateSelectorCb.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "<select>", "Today", "Yesterday", "Last week",
						"Last month" }));
		dateSelectorCb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dateSelectorCbActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(dateSelectorCb,
								javax.swing.GroupLayout.PREFERRED_SIZE, 140,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(28, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														dateSelectorCb,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addContainerGap(34, Short.MAX_VALUE)));
	}// </editor-fold>

	private void dateSelectorCbActionPerformed(java.awt.event.ActionEvent evt) {
		if (dateSelectorCb.getSelectedIndex() <= 0) {
			return;
		}
		this.selectedObject = dateSelectorCb.getSelectedItem();
		System.err.println("Selected obj = " + selectedObject);
		parent.dispose();
	}

	// Variables declaration - do not modify
	private javax.swing.JComboBox dateSelectorCb;
	private javax.swing.JLabel jLabel1;

	// End of variables declaration

	public Object getSelectedObject() {
		return this.selectedObject;
	}
}
