/*******************************************************************************
 * Copyright  
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package net.mjrz.fm.ui.dialogs.filter;

import java.awt.BorderLayout;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;

import net.mjrz.fm.ui.FinanceManagerUI;
import net.mjrz.fm.ui.dialogs.filter.FilterListModel.FilterEntry;

public class FilterDialog extends javax.swing.JPanel {

	private FinanceManagerUI parent = null;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form FilterDialog */
	private FilterDialog(FinanceManagerUI parent) {
		this.parent = parent;
		initComponents();
		setButtonState();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		fieldCb = new javax.swing.JComboBox();
		operationCb = new javax.swing.JComboBox();
		valueTf = new javax.swing.JTextField();
		saveFilterB = new javax.swing.JButton();
		cancelB = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		filterList = new javax.swing.JList();
		addParamB = new javax.swing.JButton();
		removeParamB = new javax.swing.JButton();
		clearAllB = new javax.swing.JButton();

		jLabel1.setText("Field");

		jLabel2.setText("Operation");

		jLabel3.setText("Value");

		fieldCb.setModel(new FieldCbModel());
		fieldCb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fieldCbActionPerformed(evt);
			}
		});

		relationCbModel = new RelationCbModel();
		operationCb.setModel(relationCbModel);
		operationCb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				operationCbActionPerformed(evt);
			}
		});

		valueTf.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				valueTfFocusGained(evt);
			}
		});

		saveFilterB.setMnemonic('s');
		saveFilterB.setText("Save");
		saveFilterB.setPreferredSize(new java.awt.Dimension(80, 23));
		saveFilterB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveFilterBActionPerformed(evt);
			}
		});

		cancelB.setMnemonic('c');
		cancelB.setText("Cancel");
		cancelB.setPreferredSize(new java.awt.Dimension(80, 23));
		cancelB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel4.setText("Filter Setup:");

		filterList.setModel(new FilterListModel());
		filterList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(filterList);

		addParamB.setMnemonic('A');
		addParamB.setText("Add");
		addParamB.setToolTipText("Add filter entry");
		addParamB.setPreferredSize(new java.awt.Dimension(80, 23));
		addParamB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addParamBActionPerformed(evt);
			}
		});

		removeParamB.setMnemonic('r');
		removeParamB.setText("Remove");
		removeParamB.setToolTipText("Remove selected entry");
		removeParamB.setPreferredSize(new java.awt.Dimension(80, 23));
		removeParamB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				removeParamBActionPerformed(evt);
			}
		});

		clearAllB.setMnemonic('l');
		clearAllB.setText("Clear");
		clearAllB.setToolTipText("Clear all entries");
		clearAllB.setPreferredSize(new java.awt.Dimension(80, 23));
		clearAllB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clearAllBActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														510, Short.MAX_VALUE)
												.addComponent(
														jLabel4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														510, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						fieldCb,
																						0,
																						139,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						operationCb,
																						0,
																						143,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						192,
																						Short.MAX_VALUE)
																				.addComponent(
																						valueTf,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						192,
																						Short.MAX_VALUE)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		saveFilterB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		73,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		cancelB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		73,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		addParamB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		removeParamB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		clearAllB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel4)
								.addGap(13, 13, 13)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel3)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														fieldCb,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														valueTf,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														operationCb,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														addParamB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														removeParamB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														clearAllB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1)
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														cancelB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														saveFilterB,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));
	}// </editor-fold>

	private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {
		SwingUtilities.getWindowAncestor(this).dispose();
	}

	private void saveFilterBActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void fieldCbActionPerformed(java.awt.event.ActionEvent evt) {
		String field = (String) fieldCb.getSelectedItem();
		if (field != null) {
			relationCbModel.updateModel(field);
		}
	}

	private void operationCbActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void addParamBActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void clearAllBActionPerformed(java.awt.event.ActionEvent evt) {
		FilterListModel model = (FilterListModel) filterList.getModel();
		model.removeAllElements();
		setButtonState();
	}

	private void removeParamBActionPerformed(java.awt.event.ActionEvent evt) {
		int sel = filterList.getSelectedIndex();
		FilterListModel model = (FilterListModel) filterList.getModel();
		model.removeElementAt(sel);
		filterList.setSelectedIndex(0);
		setButtonState();
	}

	private void setButtonState() {
		if (filterList.getModel().getSize() == 0) {
			clearAllB.setEnabled(false);
			removeParamB.setEnabled(false);
		}
		else {
			clearAllB.setEnabled(true);
			removeParamB.setEnabled(true);
		}
	}

	private void valueTfFocusGained(java.awt.event.FocusEvent evt) {
		filterList.requestFocusInWindow();
		String field = (String) fieldCb.getSelectedItem();
		if (field == null) {
			return;
		}
		Object val = FilterValueSelectorFactory.getSelectorValue(this, field);
		if (val != null) {
			valueTf.setText(val.toString());
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton addParamB;
	private javax.swing.JButton cancelB;
	private javax.swing.JButton clearAllB;
	private javax.swing.JComboBox fieldCb;
	private javax.swing.JList filterList;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox operationCb;
	private javax.swing.JButton removeParamB;
	private javax.swing.JButton saveFilterB;
	private javax.swing.JTextField valueTf;
	private RelationCbModel relationCbModel;

	// End of variables declaration

	public static JDialog getDialog(FinanceManagerUI parent) {
		JDialog f = new JDialog();
		f.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		f.add(new FilterDialog(parent), BorderLayout.CENTER);
		return f;
	}
}
